from WinKeyMouse import WinKeyMouse as control

if __name__ == '__main__':
    control.key_click("H")
    control.key_click("e")
    control.key_click("l")
    control.key_click("l")
    control.key_click("o")
    control.key_click(",")
    control.key_click(" ")
    control.key_click("W")
    control.key_click("i")
    control.key_click("n")
    control.key_click("K")
    control.key_click("e")
    control.key_click("y")
    control.key_click("M")
    control.key_click("o")
    control.key_click("u")
    control.key_click("s")
    control.key_click("e")
    control.mouse_down("right")
    control.mouse_up("right")
    pos = control.position()
    control.move_to(pos[0]-20, pos[1]-20)
    control.mouse_click("left")
